name: Basic Task
description: A simple task template for internal or project work
title: "[Task] "
labels: []
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Write a short description of this task.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Is this a Steering task or a Project task?
      options:
        - Steering Ops
        - Partner Project
    validations:
      required: true

  - type: input
    id: related-project
    attributes:
      label: Related Project (if any)
      description: Optional — link to a related project or partner name
      placeholder: e.g., Built Oregon, FSS, CPC
